backend:
  name: github
  repo: xx1235/xx1235.github.io   # ⬅️ 자신의 저장소
  branch: main
  base_url: https://auth.staticcms.org
  auth_endpoint: auth
  token_endpoint: auth/token
  site_domain: xn--lj2bo5c32io2r8gd.com   # 커스텀 도메인 검증 전이라면 punycode 사용


collections:
  - name: "posts"
    label: "글"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
